---
abstract: 'simple policy asserting she bang line'
author:
  - 'Jonas B. Nielsen, <jonasbn@cpan.org>'
build_requires: {}
configure_requires:
  Module::Build: 0.4
dynamic_config: 1
generated_by: 'Module::Build version 0.4005, CPAN::Meta::Converter version 2.132830'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Perl-Critic-Policy-logicLAB-RequireSheBang
provides:
  Perl::Critic::Policy::logicLAB::RequireSheBang:
    file: lib/Perl/Critic/Policy/logicLAB/RequireSheBang.pm
    version: 0.05
requires:
  List::MoreUtils: 0
  Perl::Critic: 0
  Perl::Critic::Utils: 0
  Readonly: 0
  Test::More: 0
  Test::Perl::Critic: 0
  perl: v5.8.0
resources:
  ProjectChangelog: http://logiclab.jira.com/browse/PCPLRSB#selectedTab=com.atlassian.jira.plugin.system.project%3Achangelog-panel
  ProjectSite: http://logicLAB.jira.com/browse/PCPLRSB
  ProjectWiki: http://logiclab.jira.com/wiki/display/PCPLRSB/Home
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Perl-Critic-Policy-logicLAB-Require-SheBang
  homepage: http://logiclab.jira.com/wiki/display/PCPLRSB/Home
  license: http://www.perlfoundation.org/artistic_license_1_0
  repository: https://github.com/jonasbn/pcplrsb
version: 0.05
